AC_INIT(Array.h)
AC_PREREQ(2.0)

AC_PROG_RANLIB

AC_ARG_ENABLE(gcc, [  --enable-gcc            allow use of gcc if available],
    [tk_ok=$enableval], [tkl_ok=no])
if test "$tk_ok" = "yes"; then
    AC_PROG_CC
else
    CC=${CC-cc}
AC_SUBST(CC)
fi

AC_PROG_CXX

AC_ISC_POSIX
############################################################################
# Support for automatic reconfiguration

CONFIGURE="$0 $configure_args"
AC_SUBST(CONFIGURE)
AC_OUTPUT(Makefile)
